wandb_version: 1

LEARNING_RATE:
  desc: null
  value: 0.0003
IMG_SIZE:
  desc: null
  value: 224
architecture:
  desc: null
  value: Efficientnet-b0
EPOCHS:
  desc: null
  value: 50
SEED:
  desc: null
  value: 42
BATCH_SIZE:
  desc: null
  value: 32
dataset:
  desc: null
  value: Dacon-papering-competition
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683879921.835215
    t:
      1:
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.2
      8:
      - 1
      - 3
      - 5
    framework: torch
